/// <reference types="@sveltejs/kit" />
//
interface ImportMetaEnv {
	VITE_GITHUB_CLIENT_ID: string
	VITE_OPEN_REGISTRY_BACKEND_URL: string
	VITE_OPEN_REGISTRY_ENVIRONMENT: string
	VITE_OPEN_REGISTRY_APP_NAME: string
	VITE_OPEN_REGISTRY_SUPPORT_API_KEY: string
	VITE_OPEN_REGISTRY_SUPPORT_ENDPOINT: string
	VITE_OPEN_REGISTRY_SUPPORT_EMAILS: string
}
